[package]
name = "token"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql.workspace = true
linera-sdk.workspace = true
serde.workspace = true
thiserror.workspace = true

[[bin]]
name = "token_contract"
path = "src/contract.rs"

[[bin]]
name = "token_service"
path = "src/service.rs"
